Add yamlfmt setup action
chainguard-dev/actions pull request #191
Opened 2023-01-04 23:14 UTC by puerco

This commit adds a new action called "setup-yamlfmt" that installs yamlfmt into the actions environment.

Signed-off-by: Adolfo García Veytia (Puerco) <puerco@chainguard.dev>

2023-01-04 23:31 UTC, puerco commented
Mmh I think the linter is wrong here :thinking:

2023-01-05 13:13 UTC, luhring commented on setup-yamlfmt/action.yaml
> +        esac
I _think_ the `go install <repo>@<git-ref>` syntax handles `main` and `latest` automatically, in addition to tagged versions. Would it make sense to let the `go install` command handle the version parsing here?

2023-01-05 13:14 UTC, luhring commented
> Mmh I think [the linter is wrong here](https://github.com/chainguard-dev/actions/actions/runs/3842453584/jobs/6543766083)? 🤔

Yeah, I think you're right. It looks like it's treating this YAML file as a regular GitHub Actions workflow, not as an _action_. 🤔

2023-01-10 18:35 UTC, cpanato commented
> Mmh I think [the linter is wrong here](https://github.com/chainguard-dev/actions/actions/runs/3842453584/jobs/6543766083)? 🤔

lets ignore this one

2023-02-23 08:10 UTC, cpanato requested changes
rename the action to use `.yml` and not `.yaml`

`setup-yamlfmt/action.yml`

2023-06-30 07:10 UTC, cpanato commented
@puerco do still want this?

2023-11-22 11:09 UTC, cpanato commented
@puerco gently ping

2024-09-27 07:36 UTC, cpanato commented
closing this

2024-09-27 07:36 UTC, closed without merging