Fix actionlint workflow
chainguard-dev/actions pull request #296
Opened 2023-08-14 22:41 UTC by szepeviktor

Currently actionlint's `find` command does not output the list of YAML files.

2023-08-14 22:56 UTC, szepeviktor commented
So currently we could lint `.github/workflows/*` files only.

2023-11-22 11:08 UTC, cpanato commented on .github/workflows/actionlint.yaml
> +          echo "files=$(find ./ -type f -name '*.yaml' -not -path './.chainguard/source.yaml')" >> "${GITHUB_OUTPUT}"
```suggestion
          echo "files=$(find ./ -type f -name '*.y*ml' -not -path './.chainguard/source.yaml')" >> "${GITHUB_OUTPUT}"
```

maybe?

2023-11-22 11:08 UTC, cpanato requested changes
check my comment and also please rebase

2023-11-22 11:23 UTC, szepeviktor commented
Done 🍏

2024-09-28 23:11 UTC, k4leung4 commented
obsolete with https://github.com/chainguard-dev/actions/pull/458

2024-09-28 23:11 UTC, closed without merging